<?php

namespace Database\Seeders;

use App\Models\Kelurahan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kelurahans = [
            ['kecamatan_id' => 1, 'nama' => 'Cideng', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 1, 'nama' => 'Duri Pulo', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 1, 'nama' => 'Gambir', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 1, 'nama' => 'Kebon Kelapa', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 1, 'nama' => 'Petojo Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 1, 'nama' => 'Petojo Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 2, 'nama' => 'Bendungan Hilir', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 2, 'nama' => 'Gelora', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 2, 'nama' => 'Kampung Bali', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 2, 'nama' => 'Karet Tengsin', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 2, 'nama' => 'Kebon Kacang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 2, 'nama' => 'Kebon Melati', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 2, 'nama' => 'Petamburan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 2, 'nama' => 'Slipi', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 3, 'nama' => 'Cikini', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 3, 'nama' => 'Gondangdia', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 3, 'nama' => 'Kebon Sirih', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 3, 'nama' => 'Menteng', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 3, 'nama' => 'Pegangsaan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 4, 'nama' => 'Bungur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 4, 'nama' => 'Kenari', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 4, 'nama' => 'Kramat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 4, 'nama' => 'Paseban', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 4, 'nama' => 'Senen', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 5, 'nama' => 'Cempaka Putih Barat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 5, 'nama' => 'Cempaka Putih Timur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 5, 'nama' => 'Rawasari', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 6, 'nama' => 'Galur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 6, 'nama' => 'Johar Baru', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 6, 'nama' => 'Kampung Rawa', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 6, 'nama' => 'Tanah Tinggi', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 7, 'nama' => 'Cempaka Baru', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 7, 'nama' => 'Gunung Sahari Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 7, 'nama' => 'Harapan Mulya', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 7, 'nama' => 'Kebon Kosong', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 7, 'nama' => 'Kemayoran', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 7, 'nama' => 'Serdang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 7, 'nama' => 'Sumur Batu', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 7, 'nama' => 'Utan Panjang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 8, 'nama' => 'Gunung Sahari Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 8, 'nama' => 'Kartini', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 8, 'nama' => 'Karang Anyar', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 8, 'nama' => 'Mangga Dua Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 8, 'nama' => 'Pasar Baru', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 9, 'nama' => 'Penjaringan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 9, 'nama' => 'Pluit', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 9, 'nama' => 'Pejagalan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 9, 'nama' => 'Kapuk Muara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 9, 'nama' => 'Kamal Muara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 10, 'nama' => 'Ancol', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 10, 'nama' => 'Pademangan Barat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 10, 'nama' => 'Pademangan Timur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 11, 'nama' => 'Tanjung Priok', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 11, 'nama' => 'Sungai Bambu', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 11, 'nama' => 'Papanggo', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 11, 'nama' => 'Warakas', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 11, 'nama' => 'Kebon Bawang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 11, 'nama' => 'Sunter Agung', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 11, 'nama' => 'Sunter Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 12, 'nama' => 'Koja', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 12, 'nama' => 'Tugu Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 12, 'nama' => 'Tugu Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 12, 'nama' => 'Rawabadak Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 12, 'nama' => 'Rawabadak Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 12, 'nama' => 'Lagoa', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 13, 'nama' => 'Cilincing', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 13, 'nama' => 'Kalibaru', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 13, 'nama' => 'Marunda', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 13, 'nama' => 'Rorotan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 13, 'nama' => 'Semper Barat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 13, 'nama' => 'Semper Timur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 14, 'nama' => 'Kelapa Gading Barat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 14, 'nama' => 'Kelapa Gading Timur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 14, 'nama' => 'Pegangsaan Dua', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 15, 'nama' => 'Cengkareng Barat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 15, 'nama' => 'Cengkareng Timur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 15, 'nama' => 'Duri Kosambi', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 15, 'nama' => 'Kapuk', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 15, 'nama' => 'Kedaung Kali Angke', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 15, 'nama' => 'Rawa Buaya', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 16, 'nama' => 'Grogol', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 16, 'nama' => 'Tanjung Duren Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 16, 'nama' => 'Tanjung Duren Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 16, 'nama' => 'Tomang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 16, 'nama' => 'Wijaya Kusuma', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 17, 'nama' => 'Glodok', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 17, 'nama' => 'Keagungan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 17, 'nama' => 'Krukut', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 17, 'nama' => 'Maphar', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 17, 'nama' => 'Tangki', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 18, 'nama' => 'Angke', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 18, 'nama' => 'Duri Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 18, 'nama' => 'Duri Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 18, 'nama' => 'Jembatan Besi', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 18, 'nama' => 'Jembatan Lima', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 18, 'nama' => 'Krendang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 18, 'nama' => 'Pekojan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 18, 'nama' => 'Roa Malaka', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 18, 'nama' => 'Tambora', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 19, 'nama' => 'Kalideres', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 19, 'nama' => 'Kamal', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 19, 'nama' => 'Pegadungan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 19, 'nama' => 'Semanan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 19, 'nama' => 'Tegal Alur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 20, 'nama' => 'Duri Kepa', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 20, 'nama' => 'Kebon Jeruk', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 20, 'nama' => 'Kelapa Dua', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 20, 'nama' => 'Sukabumi Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 20, 'nama' => 'Sukabumi Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 21, 'nama' => 'Gelora', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 21, 'nama' => 'Jati Pulo', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 21, 'nama' => 'Kemanggisan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 21, 'nama' => 'Palmerah', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 21, 'nama' => 'Slipi', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 22, 'nama' => 'Joglo', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 22, 'nama' => 'Kembangan Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 22, 'nama' => 'Kembangan Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 22, 'nama' => 'Meruya Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 22, 'nama' => 'Meruya Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 23, 'nama' => 'Gunung', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 23, 'nama' => 'Kebayoran Baru', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 23, 'nama' => 'Melawai', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 23, 'nama' => 'Petogogan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 23, 'nama' => 'Pulo', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 23, 'nama' => 'Selong', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 23, 'nama' => 'Senayan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 24, 'nama' => 'Grogol Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 24, 'nama' => 'Grogol Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 24, 'nama' => 'Kebayoran Lama Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 24, 'nama' => 'Kebayoran Lama Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 24, 'nama' => 'Pondok Pinang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 25, 'nama' => 'Cilandak Barat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 25, 'nama' => 'Gandaria Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 25, 'nama' => 'Lebak Bulus', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 25, 'nama' => 'Pondok Labu', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 26, 'nama' => 'Bintaro', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 26, 'nama' => 'Pesanggrahan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 26, 'nama' => 'Petukangan Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 26, 'nama' => 'Petukangan Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 26, 'nama' => 'Ulujami', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 27, 'nama' => 'Cilandak Timur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 27, 'nama' => 'Jati Padang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 27, 'nama' => 'Pejaten Barat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 27, 'nama' => 'Pejaten Timur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 27, 'nama' => 'Pasar Minggu', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 27, 'nama' => 'Ragunan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 28, 'nama' => 'Cipedak', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 28, 'nama' => 'Jagakarsa', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 28, 'nama' => 'Lenteng Agung', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 28, 'nama' => 'Srengseng Sawah', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 28, 'nama' => 'Tanjung Barat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 29, 'nama' => 'Bangka', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 29, 'nama' => 'Kuningan Barat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 29, 'nama' => 'Mampang Prapatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 29, 'nama' => 'Pela Mampang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 29, 'nama' => 'Tegal Parang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 30, 'nama' => 'Cikoko', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 30, 'nama' => 'Duren Tiga', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 30, 'nama' => 'Kalibata', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 30, 'nama' => 'Pancoran', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 30, 'nama' => 'Rawa Jati', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 31, 'nama' => 'Bukit Duri', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 31, 'nama' => 'Kebon Baru', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 31, 'nama' => 'Manggarai', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 31, 'nama' => 'Manggarai Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 31, 'nama' => 'Tebet Barat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 31, 'nama' => 'Tebet Timur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 32, 'nama' => 'Guntur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 32, 'nama' => 'Karet', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 32, 'nama' => 'Karet Kuningan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 32, 'nama' => 'Karet Semanggi', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 32, 'nama' => 'Kuningan Timur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 32, 'nama' => 'Menteng Atas', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 32, 'nama' => 'Pasar Manggis', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 32, 'nama' => 'Setiabudi', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 33, 'nama' => 'Pal Meriam', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 33, 'nama' => 'Kayu Manis', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 33, 'nama' => 'Pisangan Baru', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 33, 'nama' => 'Utan Kayu Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 33, 'nama' => 'Utan Kayu Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 34, 'nama' => 'Cipinang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 34, 'nama' => 'Jati', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 34, 'nama' => 'Jatinegara Kaum', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 34, 'nama' => 'Pisangan Timur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 34, 'nama' => 'Pulo Gadung', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 34, 'nama' => 'Rawamangun', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 35, 'nama' => 'Bali Mester', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 35, 'nama' => 'Bidara Cina', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 35, 'nama' => 'Cipinang Besar Selatan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 35, 'nama' => 'Cipinang Besar Utara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 35, 'nama' => 'Rawa Bunga', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 36, 'nama' => 'Duren Sawit', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 36, 'nama' => 'Klender', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 36, 'nama' => 'Malaka Jaya', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 36, 'nama' => 'Malaka Sari', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 36, 'nama' => 'Pondok Bambu', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 37, 'nama' => 'Batu Ampar', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 37, 'nama' => 'Cawang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 37, 'nama' => 'Cililitan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 37, 'nama' => 'Kampung Tengah', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 37, 'nama' => 'Kramat Jati', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 38, 'nama' => 'Cipinang Melayu', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 38, 'nama' => 'Halim Perdana Kusumah', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 38, 'nama' => 'Makasar', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 39, 'nama' => 'Bambu Apus', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 39, 'nama' => 'Ceger', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 39, 'nama' => 'Cilangkap', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 39, 'nama' => 'Cipayung', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 39, 'nama' => 'Lubang Buaya', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 39, 'nama' => 'Pondok Ranggon', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 40, 'nama' => 'Cibubur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 40, 'nama' => 'Kelapa Dua Wetan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 40, 'nama' => 'Mekarsari', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 40, 'nama' => 'Rambutan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 40, 'nama' => 'Susukan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 41, 'nama' => 'Cijantung', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 41, 'nama' => 'Gedong', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 41, 'nama' => 'Kalisari', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 41, 'nama' => 'Pekayon', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 41, 'nama' => 'Pasar Rebo', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 42, 'nama' => 'Cakung Barat', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 42, 'nama' => 'Cakung Timur', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 42, 'nama' => 'Jatinegara', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 42, 'nama' => 'Penggilingan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 42, 'nama' => 'Pulo Gebang', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 42, 'nama' => 'Ujung Menteng', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 43, 'nama' => 'Pulau Harapan', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 43, 'nama' => 'Pulau Kelapa', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 44, 'nama' => 'Pulau Pari', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 44, 'nama' => 'Pulau Tidung', 'created_at' => now(), 'updated_at' => now()],
            ['kecamatan_id' => 44, 'nama' => 'Pulau Untung Jawa', 'created_at' => now(), 'updated_at' => now()]
        ];

        Kelurahan::insert($kelurahans);
    }
}
